name: Run Tests

on:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use Node.js 20.5.0
        uses: actions/setup-node@v2
        with:
          node-version: 20.5.0

      - name: Install dependencies
        run: yarn install

      - name: Run tests
        run: yarn test
