name: Run Tests

on:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.1

      - name: Use Node.js 20.5.0
        uses: actions/setup-node@v4.0.0
        with:
          node-version: 20.5.0

      - name: Install dependencies and run tests
        run: |
          cd backend  # Cambia al directorio backend
          yarn install  # Instala las dependencias desde el package.json de backend
          yarn test  # Ejecuta los tests desde el package.json de backend
